config:
  target: 'http://localhost:6000'
  phases:
    - duration: 300  # Warm-up phase duration (5 minutes in seconds)
      arrivalRate: 5  # Gradually increase arrival rate
    - duration: 600  # Peak phase duration (10 minutes in seconds)
      arrivalRate: 10  # Sustain maximum arrival rate
    - duration: 300  # Cool-down phase duration (5 minutes in seconds)
      arrivalRate: 1  # Gradually decrease arrival rate

scenarios:
  - flow:
      - post:
          url: '/api/v1/users/signin'
          json:
            url: 'http://localhost:6000/api/v1/users/signin'
            expire: '{{ date }}'
          capture:
            json: $.signin
            as: 'signin'

variables:
  date:
    type: dateIso8601
    min: 2023-01-01T00:00:00.000Z
    max: 2025-12-31T23:59:59.999Z